from __future__ import annotations

from typing import Dict, List, Tuple

CAMPUS_CENTER: Tuple[float, float] = (38.9227, -77.0194)
DEFAULT_CITY = "Washington, DC"

INCIDENT_FAMILY_BY_TYPE: Dict[str, str] = {
    "Armed Robbery": "Violence",
    "Attempted Robbery": "Violence",
    "Robbery": "Violence",
    "Shooting": "Violence",
    "Shots Fired": "Violence",
    "Shooting, Attempted Robbery": "Violence",
    "Stabbing": "Violence",
    "Motor Theft": "Vehicle Incident",
    "Theft": "Property Crime",
    "Fire": "Safety Hazard",
    "Safety Hazard": "Safety Hazard",
    "Sexual Abuse": "Sexual Misconduct",
    "Sexual Misconduct": "Sexual Misconduct",
    "Suspicious Activity": "Suspicious Activity",
}

FAMILY_COLOR_MAP: Dict[str, str] = {
    "Violence": "red",
    "Vehicle Incident": "purple",
    "Property Crime": "blue",
    "Safety Hazard": "green",
    "Sexual Misconduct": "pink",
    "Suspicious Activity": "orange",
    "Other": "gray",
}

FAMILY_KEYWORDS: Dict[str, List[str]] = {
    "Sexual Misconduct": [
        "sexual abuse",
        "sexual assault",
        "sexual misconduct",
        "groped",
        "fondled",
        "unwanted touching",
        "touched the victim",
    ],
    "Property Crime": [
        "theft",
        "stolen",
        "steal",
        "larceny",
        "burglary",
        "break-in",
        "snatch",
        "shoplifting",
    ],
    "Violence": [
        "assault",
        "fight",
        "battery",
        "attack",
        "gun",
        "gunfire",
        "shooting",
        "shots fired",
        "shots",
        "stabbing",
        "stabbed",
        "stab",
        "robbery",
        "armed",
        "weapon",
        "handgun",
        "knife",
    ],
    "Suspicious Activity": [
        "suspicious",
        "unknown person",
        "lurking",
        "loitering",
        "unauthorized",
        "trespass",
    ],
    "Safety Hazard": [
        "fire",
        "smoke",
        "hazard",
        "gas leak",
        "flood",
        "alarm",
        "unsafe",
        "dumpster fire",
    ],
    "Vehicle Incident": [
        "carjacking",
        "vehicle",
        "motor theft",
        "auto theft",
        "stolen vehicle",
        "car",
        "collision",
        "hit and run",
        "scooter",
    ],
}

TYPE_KEYWORDS: Dict[str, List[str]] = {
    "Sexual Misconduct": ["sexual misconduct", "sexual assault"],
    "Sexual Abuse": ["sexual abuse", "fondled", "groped", "unwanted touching"],
    "Motor Theft": ["motor theft", "carjacking", "stolen vehicle", "auto theft"],
    "Theft": ["theft", "stolen", "larceny", "burglary", "snatch"],
    "Attempted Robbery": ["attempted robbery", "attempted armed robbery"],
    "Armed Robbery": ["armed robbery", "handgun", "armed with"],
    "Robbery": ["robbery"],
    "Shooting, Attempted Robbery": ["shooting, attempted robbery"],
    "Shooting": ["shooting"],
    "Shots Fired": ["shots fired", "gunshots", "gunshots were fired"],
    "Stabbing": ["stabbing", "stabbed", "knife attack"],
    "Fire": ["fire", "dumpster fire"],
    "Safety Hazard": ["hazard", "unsafe", "gas leak", "alarm"],
    "Suspicious Activity": ["suspicious activity", "suspicious person", "lurking"],
}

CANONICAL_LOCATIONS: Dict[str, str] = {
    "towers": "Howard Plaza Towers, Howard University, Washington, DC",
    "towers east": "Howard Plaza Towers, Howard University, Washington, DC",
    "howard plaza towers": "Howard Plaza Towers, Howard University, Washington, DC",
    "yard": "The Yard, Howard University, Washington, DC",
    "the yard": "The Yard, Howard University, Washington, DC",
    "blackburn": "Blackburn University Center, Howard University, Washington, DC",
    "blackburn center": "Blackburn University Center, Howard University, Washington, DC",
    "blackburn university center": "Blackburn University Center, Howard University, Washington, DC",
    "founders": "Founders Library, Howard University, Washington, DC",
    "founders library": "Founders Library, Howard University, Washington, DC",
    "douglass hall": "Douglass Hall, Howard University, Washington, DC",
    "c.h. best hall": "C.H. Best Hall, Howard University, Washington, DC",
    "chemistry building": "Chemistry Building, Howard University, Washington, DC",
    "wonder plaza": "Wonder Plaza, 2301 Georgia Avenue NW, Washington, DC",
    "howard university hospital": "Howard University Hospital, Washington, DC",
    "georgia ave": "Georgia Ave NW, Washington, DC",
    "georgia ave nw": "Georgia Ave NW, Washington, DC",
    "6th street nw": "6th St NW, Washington, DC",
    "sixth street nw": "6th St NW, Washington, DC",
    "500 block of w street nw": "500 block of W Street NW, Washington, DC",
    "500 block w street nw": "500 block of W Street NW, Washington, DC",
    "200 block of v street nw": "200 block of V Street NW, Washington, DC",
    "200 block of v street n.w": "200 block of V Street NW, Washington, DC",
    "500 block of college street nw": "500 block of College Street NW, Washington, DC",
    "2500 block of georgia ave": "2500 block of Georgia Ave NW, Washington, DC",
    "2500 block of georgia ave nw": "2500 block of Georgia Ave NW, Washington, DC",
    "600 block of howard place nw": "600 block of Howard Place NW, Washington, DC",
}

KNOWN_COORDINATES: Dict[str, Tuple[float, float]] = {
    "towers east": (38.92026, -77.02476),
    "towers": (38.92055, -77.02404),
    "howard plaza towers": (38.92055, -77.02404),
    "yard": (38.92319, -77.01988),
    "the yard": (38.92319, -77.01988),
    "blackburn": (38.92206, -77.02115),
    "blackburn center": (38.92206, -77.02115),
    "blackburn university center": (38.92206, -77.02115),
    "founders": (38.92228, -77.01974),
    "founders library": (38.92228, -77.01974),
    "douglass hall": (38.92163, -77.01935),
    "c.h. best hall": (38.92256, -77.02082),
    "chemistry building": (38.92190, -77.02105),
    "wonder plaza": (38.91896, -77.02255),
    "howard university hospital": (38.91760, -77.01970),
    "georgia ave nw": (38.92290, -77.02170),
    "georgia ave": (38.92290, -77.02170),
    "6th street nw": (38.91895, -77.02152),
    "sixth street nw": (38.91895, -77.02152),
    "500 block of w street nw": (38.91920, -77.02110),
    "500 block w street nw": (38.91920, -77.02110),
    "200 block of v street nw": (38.91807, -77.01948),
    "200 block of v street n.w": (38.91807, -77.01948),
    "500 block of college street nw": (38.92190, -77.02105),
    "2500 block of georgia ave": (38.92410, -77.02190),
    "2500 block of georgia ave nw": (38.92410, -77.02190),
    "600 block of howard place nw": (38.92330, -77.02130),
}

EMAIL_NOISE_PATTERNS = [
    r"preliminary investigation is being conducted.*",
    r"no further information at this time.*",
    r"please avoid the area\\.?",
    r"this is howard related\\.?",
    r"this is non-howard related\\.?",
    r"this is not a howard related incident\\.?",
    r"the complainants are not a part of the howard community\\.?",
]
